# Generated by Django 4.0.2 on 2022-03-01 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category1_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('isactive', models.CharField(blank=True, max_length=200, null=True)),
                ('created', models.DateField(blank=True, null=True)),
                ('path', models.CharField(blank=True, max_length=1000, null=True)),
                ('modify', models.DateField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='folder_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('date_upload', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'folder_tbl',
            },
        ),
        migrations.CreateModel(
            name='gallery_photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.IntegerField()),
                ('photos', models.FileField(unique=True, upload_to='Photos/')),
            ],
        ),
        migrations.CreateModel(
            name='priority_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('isactive', models.CharField(blank=True, max_length=200, null=True)),
                ('created', models.DateField(blank=True, null=True)),
                ('modify', models.DateField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='roles_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='user_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('roles', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.roles_tbl')),
            ],
        ),
        migrations.CreateModel(
            name='category2_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('isactive', models.CharField(blank=True, max_length=200, null=True)),
                ('created', models.DateField(blank=True, null=True)),
                ('modify', models.DateField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=200, null=True)),
                ('category1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.category1_tbl')),
                ('priority', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.priority_tbl')),
            ],
        ),
        migrations.CreateModel(
            name='card_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.CharField(blank=True, max_length=1500, null=True)),
                ('requested_by', models.CharField(blank=True, max_length=200, null=True)),
                ('path', models.CharField(blank=True, max_length=1000, null=True)),
                ('date_requested', models.DateField(blank=True, null=True)),
                ('status', models.IntegerField(default=0, max_length=60, null=True)),
                ('category1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.category1_tbl')),
                ('category2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.category2_tbl')),
            ],
        ),
        migrations.CreateModel(
            name='assigned_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.card_tbl')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.user_tbl')),
            ],
        ),
    ]
